#!/usr/bin/env node
/**
 * Build-time environment injection.
 *
 * Reads the four API keys from `process.env` (provided by Vercel / GitHub
 * Actions / your local shell) and writes `env.generated.js`, which sets
 * `window.__ENV`. This file is gitignored so secrets never land in the repo.
 *
 *   node scripts/build-env.mjs
 *
 * If a variable is missing it is written as an empty string — the app should
 * treat empty values as "not configured" and degrade gracefully.
 */
import fs from "node:fs";
import path from "node:path";

const KEYS = ["PADDLE_API_KEY", "OPENAI_API_KEY", "SUPABASE_KEY", "STRIPE_SECRET"];

const env = {};
for (const k of KEYS) env[k] = process.env[k] || "";

const out = `// AUTO-GENERATED by scripts/build-env.mjs — DO NOT EDIT, DO NOT COMMIT.\nwindow.__ENV = ${JSON.stringify(env, null, 2)};\n`;

fs.writeFileSync(path.join(process.cwd(), "env.generated.js"), out);
console.log(`✅ env.generated.js written (keys: ${KEYS.join(", ")}); empty values mean "not configured".`);
